# Generated by Django 5.0.6 on 2024-07-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Garcia_Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "apellido",
                    models.CharField(max_length=150, verbose_name="Contenido"),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                ("fecha_de_registro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
